{
 "title": "Kiosol",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AC Input Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (vm.time + interval '5 hours') AS \"time\",\n  vm.value as state,\n  sm.string as label\nFROM value_model vm LEFT JOIN string_map_model sm on (vm.value = sm.value AND vm.measurement_id = sm.measurement_id)\nWHERE\n  $__timeFilter(\"time\" + interval '5 hours') AND\n  (lab_id = 'kiosol') AND (vm.measurement_id = 'ac_input_state')\n  AND (device_id = 'single_phase_radian_inverters')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"time\" + interval '5 hours') AS \"time\",\n  value as voltage\nFROM value_model\nWHERE\n  $__timeFilter(\"time\" + interval '5 hours') AND\n  (lab_id = 'kiosol') AND (measurement_id = 'battery_voltage')\n  AND (device_id = 'fndcs')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Charge Controller - Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"time\" + interval '5 hours') AS \"time\",\n  value as Watts\nFROM value_model\nWHERE\n  $__timeFilter(\"time\" + interval '5 hours') AND\n  (lab_id = 'kiosol') AND (measurement_id = 'watts')\n  AND (device_id = 'charge_controllers')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"time\" + interval '5 hours') AS \"time\",\n  value as current\nFROM value_model\nWHERE\n  $__timeFilter(\"time\" + interval '5 hours') AND\n  (lab_id = 'kiosol') AND (measurement_id = 'battery_current')\n  AND (device_id = 'fndcs')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "kW Input/Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"time\" + interval '5 hours') AS \"time\",\n  value as input\nFROM value_model\nWHERE\n  $__timeFilter(\"time\" + interval '5 hours') AND\n  (lab_id = 'kiosol') AND (measurement_id = 'input_kw')\n  AND (device_id = 'fndcs')\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  (\"time\" + interval '5 hours') AS \"time\",\n  value as output\nFROM value_model\nWHERE\n  $__timeFilter(\"time\" + interval '5 hours') AND\n  (lab_id = 'kiosol') AND (measurement_id = 'output_kw')\n  AND (device_id = 'fndcs')\nORDER BY 1"
    }
   ]
  }
 ]
}